steps:

  # Docker Pull
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'katuno/apollo-server:v1']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/go-party-2023/github.com/globy-solutions/go_party-apollo_server',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/go-party-2023/github.com/globy-solutions/go_party-apollo_server']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['run', 'deploy', 'go_party-apollo_server',
           '--image', 'gcr.io/go-party-2023/github.com/globy-solutions/go_party-apollo_server',
            '--region', 'us-central1', '--allow-unauthenticated'
           ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
